# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-ams-gcto-ia-poc02

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://cramsgediteampoc01.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ae1cdc5828f545d48313bebdb86edf5f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5d9438fda0ed4135b4c35a56684bd1c3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: cramsgediteampoc01.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ae1cdc5828f545d48313bebdb86edf5f }}/finaltest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-ams-gcto-ia-poc02'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6642977057b942f39c8cb7b3aa96119d }}
        images: 'cramsgediteampoc01.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ae1cdc5828f545d48313bebdb86edf5f }}/finaltest:${{ github.sha }}'